### PR TITLE
markup copy functionality

### PR DESCRIPTION
**Pull request by malithmcr**
tried to work on  this issue: https://github.com/nickberens360/atomic-docs/issues/54
copy button on markup tab is working now.  bit hacky but works.

### CODE REVIEW

**Comment by nickberens360** [comment]
Awesome I'll check it out tomorrow. This whole app is kinda hacky so it'll fit right in:)

**Comment by malithmcr** [comment]
> Awesome I'll check it out tomorrow. This whole app is kinda hacky so it'll fit right in:)

cool. looking forward to contribute more..

**Comment by malithmcr** [comment]
Hi @nickberens360 now copy is working for all tabs. pushed new commit. could you please check ? thanks.

**Comment by nickberens360** [comment]
@malithmcr merged. thanks for the work!

**Pull request merged**
